#!/bin/sh

set -e

PRETTIER_ARGS="--write --ignore-unknown"

# format staged files
staged_files=$(git diff --cached --name-only --diff-filter=ACMR)

if [ -z "$staged_files" ]; then
    exit 0
fi

echo "$staged_files" | xargs npx prettier $PRETTIER_ARGS

# re-stage in case formatter changed anything
echo "$staged_files" | xargs git add
